language: csharp

mono: 5.2.0
dotnet: 2.1.401

install:
  # workaround for missing .net 4.5 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

script:
  # restore the repro
  - dotnet restore repro
  # build and run the FCS typecheck
  - dotnet build -v n
  - dotnet run --no-build

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
